### ISSUE TITLE
Does master work on iphone X simulator

### ISSUE THREAD

**Issue by neiljaywarner** [Norbert515/BookSearch#3]
documentation improvement if time permitting?

i have flutter configured in android studio where new project build and runs in iphone x simulator, but when i check out the project, tell it where flutter sdk is, and try to build it fails with
--
Running "flutter packages get" in BookSearch...
Launching lib/main.dart on iPhone X in debug mode...
Upgrading project.pbxproj of Runner.app' to include the 'flutter_assets' directory
Removing app.flx from project.pbxproj since it has been replaced with flutter_assets.
Warning: CocoaPods version 1.0.0 or greater not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
  For more info, see https://flutter.io/platform-plugins
To install:
  brew install cocoapods
  pod setup

Running Xcode clean...
Starting Xcode build...
Xcode build done
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    /Users/neilwarner/BookSearch/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'path_provider/PathProviderPlugin.h' file not found
    #import <path_provider/PathProviderPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by Norbert515** [comment]
That's weird. Unfortunately, I can't test it on an Apple device.

Does building work for others projects (eg. new empty project)?

**Comment by fvthree** [comment]
I tested this one. It's working fine. iOS simulator iPhone X - 11.4

**Comment by Norbert515** [comment]
thanks @fvthree, I'll close this issue then.
